### PR TITLE
Add TextChannel#canRemoveReactionsOfOthers(User)

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by BtoBastian** [comment]
I would rather call the method `canRemoveReactionsOfUser(User)` (which always returns `true`, if `user.isYourself()`).

**Comment by Vampire** [comment]
This is "can the given user delete reactions of other users in this text channel", just like the other `canXXX` methods in `TextChannel` like e. g. `canAddNewReactions(User)`.
Or did you suggest adding a second parameter?

**Comment by BtoBastian** [comment]
Ohh, my bad I misunderstood the method (which speaks for a better name).
Not sure if this method is even useful, as it's just an alias for another method.

**Comment by Vampire** [comment]
Well yes, it is just an alias for `canManageMessages`.
My intention was that the user does not need to know which technical Discord permission you need to have to remove reactions of others.
Which better name would you suggest?
`canDeleteReactionsOfOtherUsers(User)`?
`canDeleteNonOwnReactions(User)`?
`canDeleteForeignReactions(User)`?
`canDeleteOthersReactions(User)`?
Something else? (except you dismiss the method as a whole of course)

**Comment by BtoBastian** [comment]
`canRemoveReactionsOfOthers(User)` should be fine. Don't know why I misunderstood it in the first place...

**Comment by Vampire** [comment]
Ok, fine. :-)

**Pull request merged**
