### PR TITLE
Add Message#removeReactionByEmoji variants

### PR DESCRIPTION
**Pull request by Vampire**
- Add Message#removeReactionByEmoji(Emoji, User)
- Add Message#removeReactionByEmoji(String, User)
- Add Message#removeOwnReactionByEmoji(Emoji)
- Add Message#removeOwnReactionByEmoji(String)
- Add Message#removeReactionByEmoji(Emoji)
- Add Message#removeReactionByEmoji(String)

### CODE REVIEW

**Comment by BtoBastian** [comment]
What do you think about `removeOwnReactionByEmoji(...)` instead of `removeYourReactionByEmoji(...)`?

**Comment by Vampire** [comment]
I just tried to stick to your naming conventions. If it is about the bot you always have "you" / "yourself". The only occurrence where you have "own" is in "canChangeOwnNickname" and there it does not refer to the bot but to the user that is given as argument. But if you prefer "own" over "your" here, just tell me and I'll change it, I have no strong feelings about this, especially as I would have used "me", "myself" and "my" probably. :-D

**Comment by BtoBastian** [comment]
I think `own` fits fine into my naming conventions.

**Comment by Vampire** [comment]
ok, then I'll happily change it later

**Comment by Vampire** [comment]
done

**Pull request merged**
