### PR TITLE
Bulk Delete Improvement

### PR DESCRIPTION
**Pull request by Vampire**
Make TextChannel#bulkDelete methods automatically handle size and age restricitions of Discord API

### CODE REVIEW

**Comment by BtoBastian** [comment]
I'm usually not a fan of hard-codeding **any** limts/etc. at all, but in that case we can probably make an exception.
However, instead of replacing the bulk delete method with this, I would rather have a `DicordApi#deleteAll(...)` method and a `MessageSet#deleteAll()` method. These methods should also allow messages from different channels.

**Comment by Vampire** [comment]
How about `DicordApi#deleteAll(...)`, `MessageSet#deleteAll()` and `TextChannel#deleteAll(...)` and removing the `bulkDelete` messages completely?
You usually want the user to not have to care about Discord craziness, so forwarding the limitation of 2 weeks and 2-100 messages to the user is not too much in that sense I'd say, that's why I made this PR. :-)

**Comment by BtoBastian** [comment]
I still think there are usecases where you don't want to use the normal delete endpoint but just use the bulk delete endpoint and let it fail in case some of the messages are invalid.
There's no harm in keeping the bulk delete methods besides maybe a few users who didn't notice the difference between `deleteAll` and `bulkDelete`.

**Comment by Vampire** [comment]
Ok, if you think so, I'll change it to that, while I still think this more produces confusion about why there is `bulkDelete` and `deleteAll` than there is a real use-case for `bulkDelete`.

Btw. I don't think `DicordApi#deleteAll(...)` is the right place, but `Message.deleteAll(...)` is, what do you think?

**Comment by BtoBastian** [comment]
Imo it would make sense in both places.

**Comment by Vampire** [comment]
We (I did and you accpeted) moved all the message-id stuff to static message methods, so it would be the only one in DiscordApi, wouldn't it?

**Comment by BtoBastian** [comment]
Valid point.

**Comment by Vampire** [comment]
New version pushed

**Pull request merged**
