### PR TITLE
Fixes the javadocs for #ImplActivityAssets

### PR DESCRIPTION
**Pull request by GamingAndStuffs**
Adds the missing @param tag for the activity argument.

### CODE REVIEW

**Comment by GamingAndStuffs** [comment]
Pointless ;)

**Comment by Vampire** [comment]
Not pointless even if it was not the cause for the failing JavaDoc build, still a missing thing, please reopen. :-)

**Comment by BtoBastian** [comment]
Is there a reason you used `{@link ImplActivity}` instead of just `activity`?
[(Oracle's style guide)](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#styleguide) for JavaDoc comments  sums it up pretty good:

There's already a link to the class for all parameters by default, so there's no need to link it in the description of the parameter again.

**Comment by BtoBastian** [comment]
Seems like it doesn't work for PRs.
Fixed it myself now.

**Pull request closed without merging**
