### PR TITLE
Fixed double call on listener

### PR DESCRIPTION
**Pull request by Dunciboy**
The removed script parts caused double triggers when a message was
deleted, if for example you would have used delete to delete a message
the listener would be called twice for the same message.
Also changed variable logger to LOGGER since by convention rules a
static final should be in full caps.

### CODE REVIEW

**Comment by BtoBastian** [comment]
Hello, 
thank you for the pull request.

Nevertheless the variable logger was intended to be in "Lower Camel Case". Javacord is using the Google Style Guide which says that only "real" constants should be in "Upper Case".
To quote the Guide: " Every constant is a static final field, but not all static final fields are constants. "
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

**Comment by Dunciboy** [comment]
So you want me to revert the variable name change correct?

**Comment by BtoBastian** [comment]
Would be nice if you could. :)
Otherwise I would merge the pull request and change it afterwards.

**Comment by BtoBastian** [comment]
Hey,

this commit fixed the double call. It didn't remove the listener call in the delete() method but now checks in the handler if the message was already deleted.
https://github.com/BtoBastian/Javacord/commit/4e7bea2c9adecdf9415b88abec57d21ca0c4d1a9

**Pull request closed without merging**
