### PR TITLE
Add some Message#has[...] Methods

### PR DESCRIPTION
**Pull request by Kaleidox00**
Felt like those simplifying methods would come in handy.

The way I implemented them is questionable tho, correct me please.

### CODE REVIEW

**Comment by BtoBastian** [comment]
Hey,
thank you for the PR. :)

Is there really a need for such methods? I'm not sure if there are a lot of benefits of `message.hasAttachments()` vs `message.getAttachments().isEmpty()`. -> I'll ask for other opinions in #rewrite_discussion

About the implementation: All the `getAttachments()` etc. methods create new immutable collections. It would be better to use the internal object for the check to prevent this overhead.

**Comment by Kaleidox00** [comment]
Well, the internal Objects are what I dont know of where it is. This is how far I could do it and why I asked for correction. (beginner tho)

**Comment by Vampire** [comment]
To use the internal object you have to be internal of course.
You would not write default implementations, but only specify the method in the interface and implement it in its `MessageImpl` implementation where you have access to the internal objects.

**Comment by Kaleidox00** [comment]
Changed 👍 

(removed `hasChannelMentions` tho because i dont know where channelMentions are coming from?)

**Comment by BtoBastian** [comment]
After thinking about it for a while and asking in our Discord server, I don't think we need these methods.
They might be convenient in some cases, but I'm unsure if these rare cases justify the extra bloat.

I won't merge this PR for these reasons, but thank you nevertheless. Contributions are always welcome!

Some quick notes for future PR though:
- Please try to keep the style of your JavaDoc comments consistent with the other JavaDoc comments of the project. So for example, instead of 
  ```java
  /**
   * Returns whether or not the Message has any reactions
   *
   * @return True, when the message has any reactions
   */
  boolean hasReactions();
  ```
  it should be
  ```java
  /**
   * Checks if the message has any reactions.
   *
   * @return Whether the message has any reactions or not.
   */
  boolean hasReactions();
  ```
  Just search for similar methods and copy their style. :)
- Before creating a PR for a new feature, I usually recommend to ask in the Discord server first. In case the feature isn't wanted, you didn't waste your time implementing it. It's not mandatory, but especially for larger PRs I highly recommend it.

**Comment by Kaleidox00** [comment]
aighto, figured it. 

afterall, by implementing useless things you might still learn new things, and i learned a whole new stuff like this 🤔

**Comment by BtoBastian** [comment]
It's just a recommendation. I don't mind reviewing PRs. In the end it doesn't matter for me if we discuss a new feature before or after implementing it. I just thought it would save you some time, but I guess for learning it's fine. 😃

**Comment by WalkerKnapp** [comment]
Bringing up new things is always good. :) For instance, PR #277 has about a 0% chance of getting merged, but I still did it for the sake of getting people talking about it.

**Comment by Kaleidox00** [comment]
that sneaky self advertisement /lenny

**Pull request closed without merging**
