### PR TITLE
Add support for editing a roles mentionable and managed values

### PR DESCRIPTION
**Pull request by kenwiel**
I'm not sure if I did everything correctly since I'm still a beginner, but this should add support for making a Role mentionable.
I'm not sure what the managed value is used for/by but since it's also a boolean I decided to add that in as well.

### CODE REVIEW

**Comment by BtoBastian** [comment]
Thank you very much. 👍

**Comment by williamwebb** [comment]
This MR seems to have broken the build. Add a reference to a `RoleChangeManagedListener` wich does not seem to exist anywhere, as well as a few other compile errors.

**Comment by BtoBastian** [comment]
Ohh, I didn't want to merge it into the master branch.
Overlooked it, my bad ._.

**Comment by BtoBastian** [comment]
@kenwiel Can you please take a look at the problem mentioned by @williamwebb ?
Like he said, you use a RoleChangeManagedListener, which doesn't even exist.

**Pull request merged**
