### PR TITLE
Added Method Message#isPrivate

### PR DESCRIPTION
**Pull request by Kaleidox00**
Added Method Message#isPrivate which returns a boolean depending on if the Message was sent in a Private Channel (-> DM) or not.

### CODE REVIEW

**Comment by Kaleidox00** [comment]
Fixed the Grammar.

**Comment by Vampire** [comment]
8 commits for one 9 added lines, really?
Please read http://sethrobertson.github.io/GitPostProduction to learn how to use `git-rebase` to clean up that mess and in future use rebasing or the `--amend` option to `commit` right away.
Also words and phrases like "even better now", "lolz", questions and answers, "sorry", "x_x", "hello" or peoples names have no place in commit messages.
A commit message should describe what the commit does, not express random thoughts or try to communicate with certain persons. ;-)

**Comment by Kaleidox00** [comment]
Yea, that's my bad, apologies. will re open a new clean PR later on.

**Comment by Vampire** [comment]
You don't need a new PR, just fix up your commit history and force-push the branch from which you opened the PR. As long as the PR is not closed, this will update the PR with the new state.

**Comment by Kaleidox00** [comment]
Updated the commits to reasonable and proper names, also dropped some useless commits.

**Comment by Vampire** [comment]
Well, now you should probably rebase your work to current v_3 state.
Your work is based off a commit from 2018-02-24.
Hence the CircleCI build breaks and GitHub shows that there are conflicts you have to resolve first.

**Pull request closed without merging**
