### PR TITLE
Add API to fetch a single message from a channel

### PR DESCRIPTION
**Pull request by MedicOP**
#71

### CODE REVIEW

**Comment by MedicOP** [comment]
I forgot to add the public modifier in the interface but it is redundant anyway

**Comment by BtoBastian** [comment]
Great, thank you! :-)
Can you please add a check, if the message isn't cached, before sending a request to Discord? I can also add it myself, if you don't want to.

**Comment by MedicOP** [comment]
I'm really bad at using Git so I don't know how to do it without messing up the repo lol, please feel free to do it

**Comment by BtoBastian** [comment]
Ok :-)

**Comment by BtoBastian** [comment]
Hey,
I created a own commit based on your PR. Thank you!
https://github.com/BtoBastian/Javacord/commit/3be578ff67ee4f12bdd76b3d8e1a687fe711e6ea

**Pull request closed without merging**
