### PR TITLE
Implement UserJoin/LeaveVoiceChannelListener

### PR DESCRIPTION
**Pull request by shawishi**
Only minimal join/leave VC events thus far; Mainly because I intend to use said events in a bot I'm developing.
Tested.

### CODE REVIEW

**Comment by shawishi** [comment]
Yay added VoiceChannel#getConnectedUsers and User#getVoiceChannel! (Fully tested)
Note: Right now it doesn't init with Users that were connected to the channel before the bot had successfully connected. Not entirely sure how that could be done, but it's something to consider for the future :) @BtoBastian

**Comment by 567legodude** [comment]
That information is provided along with the server info. Inside one of the server classes while all the information is being read from discord, the connected user information can also be retrieved.

**Comment by shawishi** [comment]
Great, I'm looking at the Discord documentation but I can't really see that in any of the documented response bodies. Is it in the Guild JSON?

**Comment by shawishi** [comment]
Found it in the Guild on GUILD_CREATE's JSON as `voice_states`. Will implement and add to this PR soon.

**Comment by shawishi** [comment]
And now it's completely ready imo. @BtoBastian pls review :)

**Comment by BtoBastian** [comment]
Hey,
thank you for your PR!

**Comment by shawishi** [comment]
:)

**Comment by BtoBastian** [comment]
But I'll replace the Tabs with Spaces :p

**Comment by shawishi** [comment]
Fair enough. I'll be sure to switch my Eclipse settings next time.

**Pull request merged**
